CREATE DATABASE ATVIDADE21;

USE ATVIDADE21;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(50)
);

CREATE TABLE VENDEDOR(
    ID_VENDEDOR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_VENDEDOR VARCHAR(50),
    IDADE INT
);

CREATE TABLE MARCA(
    ID_MARCA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_MARCA VARCHAR(50)
);

CREATE TABLE VEICULO(
    ID_VEICULO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    VALOR DECIMAL(10,2),
    NOME_MODELO VARCHAR(50),
    MARCA_ID INT,

    FOREIGN KEY(MARCA_ID)
    REFERENCES MARCA(ID_MARCA)
);

CREATE TABLE VENDA(
    ID_VENDA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CLIENTE_ID INT,
    VEICULO_ID INT,
    VENDEDOR_ID INT,

    FOREIGN KEY(CLIENTE_ID)
    REFERENCES CLIENTE(ID_CLIENTE),

    FOREIGN KEY(VEICULO_ID)
    REFERENCES VEICULO(ID_VEICULO),

    FOREIGN KEY(VENDEDOR_ID)
    REFERENCES VENDEDOR(ID_VENDEDOR)

);
INSERT INTO CLIENTE VALUES(NULL,"ROBSON");
INSERT INTO CLIENTE VALUES(NULL,"SILVANIELE");
INSERT INTO CLIENTE VALUES(NULL,"FELINA");
INSERT INTO CLIENTE VALUES(NULL,"JARED");
INSERT INTO CLIENTE VALUES(NULL,"MARCOS");
INSERT INTO CLIENTE VALUES(NULL,"MARIA");

INSERT INTO MARCA VALUES (NULL,"FIAT");
INSERT INTO MARCA VALUES (NULL,"CHEVROLET");
INSERT INTO MARCA VALUES (NULL,"TOYOTA");

INSERT INTO VENDEDOR VALUES(NULL,"MARCOS",50); 
INSERT INTO VENDEDOR VALUES(NULL,"PAULO",38);
INSERT INTO VENDEDOR VALUES(NULL,"ANDRE",25); 
INSERT INTO VENDEDOR VALUES(NULL,"JUNIOR",47); 
INSERT INTO VENDEDOR VALUES(NULL,"CARLOS",59); 
INSERT INTO VENDEDOR VALUES(NULL,"MARCOS",27);

INSERT INTO VEICULO VALUES(NULL,22911,"PALIO",1);
INSERT INTO VEICULO VALUES(NULL,82356,"CRONOS",1);
INSERT INTO VEICULO VALUES(NULL,56247,"ARGO",1);
INSERT INTO VEICULO VALUES(NULL,40325,"ONIX",2);
INSERT INTO VEICULO VALUES(NULL,60356,"CRUZE",2);
INSERT INTO VEICULO VALUES(NULL,21420,"SPIN",2);
INSERT INTO VEICULO VALUES(NULL,70659,"COROLA",3);
INSERT INTO VEICULO VALUES(NULL,80965,"HILLUX",3);
INSERT INTO VEICULO VALUES(NULL,87452,"SW4",3);


INSERT INTO VENDA VALUES(NULL,1,1,2);
INSERT INTO VENDA VALUES(NULL,2,2,3);
INSERT INTO VENDA VALUES(NULL,3,3,4);
INSERT INTO VENDA VALUES(NULL,4,4,5);
INSERT INTO VENDA VALUES(NULL,5,5,6);
INSERT INTO VENDA VALUES(NULL,6,6,1);
INSERT INTO VENDA VALUES(NULL,5,7,2);
INSERT INTO VENDA VALUES(NULL,4,8,3);
INSERT INTO VENDA VALUES(NULL,3,9,4);
INSERT INTO VENDA VALUES(NULL,2,10,2);
INSERT INTO VENDA VALUES(NULL,1,11,1);
INSERT INTO VENDA VALUES(NULL,3,1,2);
INSERT INTO VENDA VALUES(NULL,4,1,3);
INSERT INTO VENDA VALUES(NULL,5,2,4);
INSERT INTO VENDA VALUES(NULL,6,2,1);
INSERT INTO VENDA VALUES(NULL,5,3,2);
INSERT INTO VENDA VALUES(NULL,4,3,3);
INSERT INTO VENDA VALUES(NULL,3,4,4);
INSERT INTO VENDA VALUES(NULL,2,4,1);
INSERT INTO VENDA VALUES(NULL,1,5,2);
INSERT INTO VENDA VALUES(NULL,2,5,3);
INSERT INTO VENDA VALUES(NULL,3,6,4);
INSERT INTO VENDA VALUES(NULL,4,7,5);
INSERT INTO VENDA VALUES(NULL,5,2,6);
INSERT INTO VENDA VALUES(NULL,6,1,5);
INSERT INTO VENDA VALUES(NULL,5,2,4);
INSERT INTO VENDA VALUES(NULL,4,4,3);
INSERT INTO VENDA VALUES(NULL,3,6,2);
INSERT INTO VENDA VALUES(NULL,2,7,1);
INSERT INTO VENDA VALUES(NULL,1,8,2);
INSERT INTO VENDA VALUES(NULL,2,9,3);
INSERT INTO VENDA VALUES(NULL,1,10,4);
INSERT INTO VENDA VALUES(NULL,2,11,5);
INSERT INTO VENDA VALUES(NULL,2,9,6);
INSERT INTO VENDA VALUES(NULL,3,10,4);
INSERT INTO VENDA VALUES(NULL,4,2,3);

/*1 - Exiba a marca e modelo do veículo mais barato*/

SELECT  NOME_MODELO, NOME_MARCA FROM MARCA
INNER JOIN VEICULO
ON MARCA_ID = ID_MARCA
HAVING MIN(VALOR);

/*2 - Exiba o modelo e a quantidade do veículo mais vendido.*/ 
    SELECT NOME_MODELO, COUNT(NOME_MODELO) AS "MODELO" FROM VEICULO
    INNER JOIN VENDA
    ON VEICULO_ID = ID_VEICULO
    GROUP BY NOME_MODELO
    HAVING MAX(MODELO);

3 - Exiba os nomes dos clientes que compraram o veículo Palio
SELECT NOME_CLIENTE, NOME_MODELO FROM CLIENTE
INNER JOIN VENDA
ON CLIENTE_ID = ID_CLIENTE
INNER JOIN VEICULO
ON VEICULO_ID = ID_VEICULO
WHERE NOME_MODELO = "PALIO";


4 - Exiba o nome do cliente que comprou o carro mais caro
SELECT NOME_CLIENTE, VALOR FROM CLIENTE
INNER JOIN VENDA
ON CLIENTE_ID = ID_CLIENTE
INNER JOIN VEICULO
ON VEICULO_ID = ID_VEICULO
HAVING MAX(VALOR);
5 - Exiba o nome e o total de veículos vendidos por cada vendedor
SELECT NOME_VENDEDOR SUM(VALOR) FROM VENDEDOR
INNER JOIN VENDA
ON 
