/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE SORVETERIA;

/*CONECTANDO AO BANCO DE DADOS*/
USE SORVETERIA;

/*CRIANDO A TABELA PRODUTO*/
CREATE TABLE PRODUTO(
    ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45),
    DATA_VALIDADE DATE,
    DATA_FABRICACAO DATE,
    VALOR DECIMAL(10,2)
);

/*CRIANDO TABELA CLIENTE*/
CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(45),
    NOME VARCHAR(45),
    ENDERECO_ID INT
);

/*CRIANDO A TABELA ENDEREÇO*/
CREATE TABLE ENDERECO(
    ID_ENDERECO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CEP VARCHAR(45),
    BAIRRO VARCHAR(45),
    CIDADE_ESTADO VARCHAR(45),
    LOGRADOURO VARCHAR(45)
);

/*CRIANDO A TABELA FORMA_PAGAMENTO*/
CREATE TABLE FORMA_PAGAMENTO(
    ID_PAGAMENTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(45)
);

/*CRIANDO A TABELA PEDIDO*/
CREATE TABLE PEDIDO(
    ID_PEDIDO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PAGAMENTO_ID INT,
    CLIENTE_ID INT,
    PRODUTO_ID INT
);

/*COLOCANDO OS RELACIONAMENTOS DAS TABELAS*/
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY(ENDERECO_ID)
REFERENCES ENDERECO(ID_ENDERECO);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_PAGAMENTO FOREIGN KEY(PAGAMENTO_ID)
REFERENCES FORMA_PAGAMENTO(ID_PAGAMENTO);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(CLIENTE_ID)
REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY(PRODUTO_ID)
REFERENCES PRODUTO(ID_PRODUTO);


INSERT INTO ENDERECO VALUES(NULL,"60767-702","Mondubim","Fortaleza,CE","RUA 01");
INSERT INTO ENDERECO VALUES(NULL,"60752-010","Mondubim","Fortaleza,CE","AVENIDA 1");
INSERT INTO ENDERECO VALUES(NULL,"60767-725","Mondubim","Fortaleza,CE","RUA 1");
INSERT INTO ENDERECO VALUES(NULL,"60544-760","Siqueira","Fortaleza,CE","RUA 01");
INSERT INTO ENDERECO VALUES(NULL,"60544-763","Siqueira","Fortaleza,CE","RUA 02");
INSERT INTO ENDERECO VALUES(NULL,"60544-766","Siqueira","Fortaleza,CE","RUA 03");
INSERT INTO ENDERECO VALUES(NULL,"61905-430","Novo Maracanaú","Maracanaú,CE","RUA 1");
INSERT INTO ENDERECO VALUES(NULL,"61905-530","Novo Maracanaú","Maracanaú,CE","RUA 10");
INSERT INTO ENDERECO VALUES(NULL,"61905-540","Novo Maracanaú","Maracanaú,CE","RUA 11");

INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0001","João Silva",1);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0002","Maria Costa",1);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0003","Pedro Soares",2);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0004","Leandro Silva",3);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0005","Ana Soares",4);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0006","Patricia Costa",4);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0007","Pedro Silva",5);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0008","Otavio Soares",6);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0009","João Costa",7);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0010","Davi Silva",8);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0021","John Silva",9);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0011","João Maria",1);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0012","Mário da Costa",2);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0013","Pedro Leonardo",3);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0014","Will Bank",4);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0015","Weberson Inácio",5);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0016","Jair Silva",6);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0017","Vitor Melo",7);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0018","Guilherme Soares",8);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0019","Gustavo Lima",9);
INSERT INTO CLIENTE(CPF,NOME,ENDERECO_ID) VALUES("0020","Pedro Nascimento",9);

INSERT INTO FORMA_PAGAMENTO(DESCRICAO) VALUES("Cartão de Credito");
INSERT INTO FORMA_PAGAMENTO(DESCRICAO) VALUES("Cartão de Débito");
INSERT INTO FORMA_PAGAMENTO(DESCRICAO) VALUES("PIX");
INSERT INTO FORMA_PAGAMENTO(DESCRICAO) VALUES("Dinheiro");
INSERT INTO FORMA_PAGAMENTO(DESCRICAO) VALUES("Vale Alimentação");

INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Picolé limão","2022-03-31","2022-11-01",5.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Picolé Morango","2022-03-31","2022-11-01",5.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Picolé Chocolate","2022-11-01","2022-10-01",5.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Picolé Ovomaltine","2022-11-01","2022-10-01",5.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Pote morango","2022-11-01","2022-05*-10",10.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Pote Café","2022-03-31","2022-05-10",10.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Pote Cajá","2022-06-10","2022-05-10",10.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Pote Tapioca","2022-06-10","2022-12-01",10.99);
INSERT INTO PRODUTO(NOME,DATA_VALIDADE, DATA_FABRICACAO, VALOR) VALUES("Açai","2022-06-10","2022-06-10",14.99);


INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(1,1,1);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(2,2,2);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(3,3,3);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(4,4,4);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(5,5,5);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(3,6,6);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(2,7,7);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(1,8,8);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(4,9,9);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(5,10,9);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(2,11,8);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(3,12,7);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(1,13,4);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(1,2,5);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(1,4,6);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(2,5,1);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(2,6,2);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(3,10,3);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(3,10,3);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(3,10,6);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(3,4,9);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(4,6,8);
INSERT INTO PEDIDO(PAGAMENTO_ID,CLIENTE_ID, PRODUTO_ID) VALUES(4,5,5);




/* 1- Quantos clientes tem cadastrado no banco de dados? */
    SELECT COUNT(NOME) AS CLIENTE FROM CLIENTE;

/* 2- Qual o faturamento total da empresa? */
    SELECT SUM(VALOR) AS FATURAMENTO FROM PRODUTO
    INNER JOIN PEDIDO
    ON PRODUTO_ID = ID_PRODUTO;

/* 3- Quantos clientes moram em Maracanaú? */
    SELECT CIDADAE_ESTADO AS ESTADO,count(NOME) AS "QUANTIDADE DE PESSOAS" FROM ENDERECO
    INNER JOIN CLIENTE
    ON ENDERECO_ID = ID_ENDERECO
    WHERE CIDADAE_ESTADO LIKE '%maracanau%';

/* 4- Quais produtos cada cliente comprou? */
    SELECT C.NOME AS CLIENTE, PR.NOME AS PRODUTO FROM CLIENTE C
    INNER JOIN PEDIDO P
    ON P.CLIENTE_ID = ID_CLIENTE
    INNER JOIN PRODUTO PR
    ON PRODUTO_ID = ID_PRODUTO;

/* 5- Quais produtos irão vencer após o dia 20/09/2022? */
    SELECT NOME,DATA_VALIDADE FROM PRODUTO
    WHERE DATA_VALIDADE > "2022-09-20";

/* 6- Quais produtos foram fabricados no dia 01/11/2022? */
    SELECT NOME FROM PRODUTO
    WHERE DATA_FABRICACAO = "2022-11-01";

/* 7- Quantos clientes pagaram por meio do PIX? */
    SELECT DESCRICAO AS "FORMA DE PAGAMENTO" ,COUNT(NOME) AS QUANTIDADE FROM CLIENTE
    INNER JOIN PEDIDO
    ON CLIENTE_ID = ID_CLIENTE
    INNER JOIN FORMA_PAGAMENTO
    ON PAGAMENTO_ID = ID_PAGAMENTO
    WHERE DESCRICAO = "PIX";

/* 8- Qual seria o valor dos produtos se for aplicado 10% de desconto? */
SELECT NOME, VALOR * 0.90 as "COM 10% OFF" FROM PRODUTO;

/* 9- Quais os produtos comprados por Pedro Soares? */
SELECT C.NOME AS CLIENTE, PR.NOME AS PRODUTO FROM CLIENTE C
INNER JOIN PEDIDO P
ON P.CLIENTE_ID = ID_CLIENTE
INNER JOIN PRODUTO PR
ON PRODUTO_ID = ID_PRODUTO
WHERE C.NOME = "Pedro Soares";
 